### ISSUE TITLE
auto reconnect

### ISSUE THREAD

**Issue by genuinefafa** [davinkevin/AngularStompDK#13]
I'm reading this [article](http://g00glen00b.be/spring-angular-sockjs/) and the are proposing a nice way to reconnect stomp on timeout. But I'm unable to do it using `ngstomp`. 

Whats the correct way to do it?

**Comment by davinkevin** [comment]
This article propose to reconnect with the onclose function on the stompClient.

But, I don't find any information about this element in the official Stomp-Websocket-JS documentation (http://jmesnil.net/stomp-websocket/doc/).

The best implementation in AngularStompDK seems to add an attribute on configuration to define if we want to reconnect on close.

For other behaviour (for example, modify a controller value on close), we will need an other callback function define on the service invocation.

I will do some investigation as soon as possible (maybe this week-end), and I will let you know.
Don't forge, you can do a PR if you want to help.

Thanks

**Comment by genuinefafa** [comment]
Interesting. I was pretty sure that `reconnect` behavior was part of the specification. You are right, it is not. However, the [source code](https://github.com/jmesnil/stomp-websocket/blob/master/src/stomp.coffee#L317) for the *stomp-websocket* does have that method.

I'm not a _expert user_ of this tecnologies. That's why I am at the _read article and comment with reference user_ stage.

Do you think I can help? I'm more than ready to do that. Just point me in the right direction and I'll do my best. :metal:

**Comment by davinkevin** [comment]
You can help, you just have to test and check if a behavior can be associated with the onclose of Stomp. 
I'm building a little backend app to ease the testing of the lib (https://github.com/davinkevin/spring-websocket-disconnect) and I'm trying to add a custom behavior...

For the API modification, let me now what you prefer (just an element on config to auto-reconnect) or a special behavior for each call to ngStompProvider ?

**Comment by davinkevin** [comment]
I've modified the onclose callback of the StompClient (https://github.com/davinkevin/spring-websocket-disconnect/blob/master/src/main/resources/static/angularStompDK.js#L198), it's never called... 
I've tried with a connection closed from the server and from the browser...

All the code is here : https://github.com/davinkevin/spring-websocket-disconnect

I don't have much time today, I will try to work on it... because the auto-reconnect is something I would like to add.

**Comment by genuinefafa** [comment]
@davinkevin i'm watching this but some other matters are taking my full attention... i'll catch up with this soon and get back to you! thanks for your quick reply ;)

**Comment by davinkevin** [comment]
I don't find any solution for this use case. Do you find something to enable the auto-reconnection ?

**Comment by genuinefafa** [comment]
It is strange. Have the same issue here (at least with Chrome). Then I do some googleing, check [this out](http://stackoverflow.com/a/31073984/1098814). 

Apparently the alternative is to add some logic [here](https://github.com/davinkevin/spring-websocket-backend/blob/master/src/main/resources/static/angularStompDK.js#L107) to throw disconnection event.

Is it right?

**Comment by davinkevin** [comment]
Handle some logic in the 'error callback' of connection promise seems strange for me.

A promise is evaluated only once, so if the promise succeed once, it will never reach the error callback.
That's why I've searched in the StompClient disconnect callback, but without any success.

Keep working on it.

**Comment by davinkevin** [comment]
I've implemented it very simply (example here : https://github.com/davinkevin/spring-websocket-backend)

If the error callback of the stomp client is called, I reconnect by using all the parameters gave to the service before (I store it now...)

This behavior is not triggered if disconnection made manually.

Say me if it's alright for your need

**Comment by davinkevin** [comment]
Add in 0.6.1 a timeOut parameter to configure the waiting time between two try of reconnection. 
Without it, the system reach StackOverflow... 

By default, the system is waiting 5 Seconds between each try, this value could be changed by the provider.

**Comment by genuinefafa** [comment]
Excellent! :+1:
