### ISSUE TITLE
Ability to change heartbeat values

### ISSUE THREAD

**Issue by jarace87** [davinkevin/AngularStompDK#15]
The Stomp.js library has the ability to change the incoming and outgoing heartbeat values on the client.  I'm interested in using AngularStompDK but need to be able to change these heartbeat values.  It would be nice to be able to do this via the config.

**Comment by davinkevin** [comment]
You want to change the heart-beat timing value define with 

```js 
client.heartbeat.outgoing = 20000; // client will send heartbeats every 20000ms
client.heartbeat.incoming = 0;     // client does not want to receive heartbeats
                                       // from the server
```

In the config stage, something like this could do the job ? 
```js
angular.module('myApp')
        .config(function(ngstompProvider){
            ngstompProvider
                .url('/ws')
                .credential('login', 'password')
                .heartbeat(20000, 0) // .heartbeat(outgoing, incoming)
        });
```

**Comment by jarace87** [comment]
Yes, that could work.

**Comment by davinkevin** [comment]
Done in a43c52d602468ca62190bf63eedd71df49bcc929

Hope that will help you.

If in the futur I can't do the modification, don't forget, you can do a PR...

You close the issue if it's ok for you ;)

**Comment by jarace87** [comment]
Great, thanks for the quick response! Will definitely submit a PR if I discover anything else in future.
