### ISSUE TITLE
Stomp undefined?

### ISSUE THREAD

**Issue by lpotapczuk** [davinkevin/AngularStompDK#16]
Hey guys!

I've just downloaded your project, and whenever I try to run it, I have an issue where 'Stomp' is undefiend in the following line:

            this.Stomp = Stomp;

I couldn't find any information, whether or not I need to download any additional plugins - so I assume that I don't have to download them for the client(browser) side.

Thanks

**Comment by lpotapczuk** [comment]
I just had to install stompjs through npm ;)

**Comment by davinkevin** [comment]
Ok, I should explain this in the Readme. Do we have a solution to force the installation during npm install ? 
I just add to bower and JSPM repository, something should be done for npm I think.

**Comment by lpotapczuk** [comment]
Remember, that also ng stomp requires three other packages. I think it would be good to mention this in description.

**Comment by lpotapczuk** [comment]
By the way, do you plan to introduce definitions for the package for typescript? If not, I may do that, as we need it in our company.

**Comment by davinkevin** [comment]
I don't work with TypeScript right now for some reason (I don't find a good tools to generate coverage report like istambul). But, if you want to do a PR on this repo and/or on https://github.com/DefinitelyTyped/DefinitelyTyped it would be good for me !

**Comment by lpotapczuk** [comment]
Alright! I don't promise, but I may eventually do that. I will give you an access to the repo when I will be working on it, so that you can have a look on it.

**Comment by davinkevin** [comment]
Thanks
