### ISSUE TITLE
Adding it to webjars

### ISSUE THREAD

**Issue by zeroows** [davinkevin/AngularStompDK#25]
Can you please add this great lib to Webjars.

http://www.webjars.org/request

**Comment by davinkevin** [comment]
The library already exist, but the version 0.6.2 wasn't pushed.

We have to wait few hours to see it in maven repo.

We will close this issue when Maven repo will have it.

;)

**Comment by davinkevin** [comment]
All seems to be available : http://search.maven.org/#search%7Cgav%7C1%7Cg%3A%22org.webjars.bower%22%20AND%20a%3A%22AngularStompDK%22

I am currently adding the version 0.8.0
