### ISSUE TITLE
Angular 2?

### ISSUE THREAD

**Issue by Yermo** [davinkevin/AngularStompDK#29]
Any plans to implement a version for Angular 2?

**Comment by davinkevin** [comment]
I'm working on Angular2 right now for other project... and I'm wondering if a wrapper around StompJS would be necessary. AngularStompDK is mainly a bridge between StompJS and AngularJS Digest Cycle.

With Angular2, this kind of bridge seems to not be necessary. So I'll maybe do something to preserve the fluent API of AngularStompDK for Angular2, but I think you can use StomJS right now in your Angular2 project...

**Comment by Yermo** [comment]
Thank you for the quick reply. That does make sense.

**Comment by davinkevin** [comment]
Say me if you try StompJS with Angular2, I'll be glad to know if it's working well :smile:

**Comment by davinkevin** [comment]
I've checked and thanks to ZoneJS which monkeyPatch all browser API, all the behavior of StompJS should be working in Angular2.

I close this issue to reduce the number of issue 😄
