### ISSUE TITLE
providing relative URL without protocol and hostname doesnt work

### ISSUE THREAD

**Issue by mihn** [davinkevin/AngularStompDK#3]
```javascript
 .config(function (ngstompProvider) {
        ngstompProvider
            .url('ws://localhost:9000/websocket');
    })
```
does work, but when used as in readme:
```javascript
 .config(function (ngstompProvider) {
        ngstompProvider
            .url('/websocket');
    })
```
it doesnt. 
At this moment i have to use following hack:
```javascript
 .config(function (ngstompProvider) {
        ngstompProvider
            .url('ws://' + window.location.host + '/websocket');
    })
```

**Comment by davinkevin** [comment]
Thanks for this information, I will treat this issue as soon as possible.

**Comment by mihn** [comment]
Another issue might be detecting to use wss, when page is using https.

**Comment by davinkevin** [comment]
I will treat both with this issue.
The goal is to use following syntax : 
* /websocket
* //localhost:9000/websocket 
* ws://localhost:9000/websocket

The first will use the same protocol and host, the second only the protocol and the third, the whole url.
If you have idea of implementation, you can do a PR if you want to contribute ;)

**Comment by davinkevin** [comment]
For information, do you work with SockJS ? In my other project using AngularStompDK, I use the config with just the path and everything works (https://github.com/davinkevin/Podcast-Server/blob/master/src/main/resources/static/app/js/modules/config/ngstomp.config.es6.js)

I suspect SockJS to do the path resolution on its own.

**Comment by mihn** [comment]
No. Plain stomp.
1 lip 2015 12:12 "Davin Kevin" <notifications@github.com> napisał(a):

**Comment by mihn** [comment]
Just tested and it works fine with SockJS :+1:

**Comment by davinkevin** [comment]
I've search a lot of "simple" solution to provide what I explain the 1 July, but it seems I need to do all the parsing in the provider part...

I don't think this add a lot of value, SockJS enable it by default, Stomp doesn't, and using an external dependency (like URL.js or others) isn't in the spirit of the AngularStompDK (simple and light).

The hack you use is a straightforward solution and do the job right now... So I tag it WONTFIX and close the ticket.
