### ISSUE TITLE
Multiple subscriptions to the same topic after reconnect 

### ISSUE THREAD

**Issue by baczus** [davinkevin/AngularStompDK#30]
Hi,
I noticed that after each reconnect, library connects to the same topic multiple times.
To be more clear. After first reconnect we have two subscriptions, after second reconnect four subscriptions and so on.
I think this is related to changes made in 9898775 and fact that after reconnect, library executes _$$addToConnectionQueue_ function:
_$reconnectAll()_ -> _this.subscribe()_ -> _this.$stompSubscribe()_ -> _this.$$addToConnectionQueue()_

**Comment by davinkevin** [comment]
Ok, I'll try to solve it. 

And it seems the reconnectAll doesn't remove all the subscriptions before "reconnecting everything".
I think, reseting the `this.connection` array could be the simple way to solve it.

If you want, you can do a Pull request :+1:

**Comment by davinkevin** [comment]
Close by #31
