### ISSUE TITLE
"ERROR message:Bad CONNECT

### ISSUE THREAD

**Issue by shashankel** [davinkevin/AngularStompDK#34]
I keep getting the below message
"ERROR message:Bad CONNECT content-type:text/plain version:1.0,1.1,1.2 content-length:38 Virtual host 'undefined' access denied"

My provider configuration:
         ngstompProvider
                .url('http://172.21.133.222:15674/stomp')
                .credential('guest','guest')
                .class(SockJS);    

Libraries used:
Stomp JS: 1.7.1
Sock JS: 0.3.4

**Comment by davinkevin** [comment]
You use some old version of libraries (Stomp is in v2.3) and SockJS is now in 1.0.3.

Could you first try to connect with just StompJs and without AngularJS to see if the problem is link to AngularStompDK or Stomp himself...

**Comment by shashankel** [comment]
Adding .vhost('/') resolved the problem. Thanks

**Comment by davinkevin** [comment]
Ok, but I advice you to upgrade your lib version 👍

**Comment by shashankel** [comment]
Yes. Upgraded to latest

**Comment by michaelkrog** [comment]
I had the same issuse using the latest version against Rabbitmq. Adding .vhost('/') solves it.
