### ISSUE TITLE
Is it possible to change the auto reconnect behaviour?

### ISSUE THREAD

**Issue by helara** [davinkevin/AngularStompDK#35]
For what I can see in the library, all I can control is the waiting time between two tries of reconnection; but I actually would like to disable "auto reconnect" altogether, and be in control of what happens after a disconnection.

Thanks in advance.

**Comment by davinkevin** [comment]
I think this could be part of the configuration, with the default timing between two connection set to `-1` to disable auto-reconnect.

I have another request about the auto-reconnect, so I think, if no one proprose a PR, I will do both of them in same time... but I don't know when, sorry.

Feel free to propose if you want 👍

**Comment by davinkevin** [comment]
I've made some modification on master to allow disabling the auto-reconnect function. 
For that, you have to set a timeOut value to less than 0.

Could you test and say if it's ok for you like that ? If yes, I'll do a bump / release.

😄

**Comment by helara** [comment]
Great! I'll test it and I'll let you know. Thanks a lot :smile:

**Comment by davinkevin** [comment]
Done in 0.8.2, open an issue if not working as expected
