### ISSUE TITLE
Uncaught TypeError: scope.$applyAsync is not a function

### ISSUE THREAD

**Issue by baczus** [davinkevin/AngularStompDK#39]
Hi,

on the latest version (0.9.0) I got following error:
```
Uncaught TypeError: scope.$applyAsync is not a function
   (anonymous function)	@	angular-stomp.js:401
   (anonymous function)	@	stomp.js:309
```
in function _$stompSubscribe_:
```
scope.$applyAsync(function () {
   return callback(message);
});
```
Problem occurs, because empty object for scope is created in function _SubscribeBuilder.subscribeTo_ and because of that this condition _if (scope === undefined)_ in _$stompSubscribe_ is insufficient.

**Comment by davinkevin** [comment]
I haven't test this way... sorry 😞

**Comment by baczus** [comment]
Thanks for quick response :)
