### ISSUE TITLE
Is there a callback for reconnect ?

### ISSUE THREAD

**Issue by sakthig** [davinkevin/AngularStompDK#41]
I am using ngStompProvider to start the websocket connection, but it is not returning any promise. Is there a callback or a promise which can be used in the event on websocket reconnection.

**Comment by davinkevin** [comment]
Right now, the connection is launched automatically after the service is created (in constructor). This could be a problem for what you are asking. But, you can access the `promise`  used during the connection process https://github.com/davinkevin/AngularStompDK/blob/master/core/service.js#L39

But, Stomp can fire the connection callback and the disconnect callback, so I don't think this will work well with the reject / resolve on the same promise.

Could you show in this issue what you would like to see in term of API in AngularStompDK to achieve this ? I would like to understand what is your need. 

Thanks

**Comment by sakthig** [comment]
Below are the issues i am facing, not sure if it has to do with AngularStompDK.

1. First my app connects to the web socket using ngstompProvider .. after this i subscribe to a channel using ngstomp.subscribeTo.
Suppose there is re-connection happening, only the web socket connects again.. it is not subscribing to the channel during re-connection. Hence i was looking for a callback that can i can use to subscribe again. May be there can be an additional 'callback function' input for ngstompProvider which will be invoked whenever connection or reconnection happens.

2. I tried to use that promiseResult.. but looks like during re-connection that promise is being overwritten.  [Pls Check this code](https://github.com/davinkevin/AngularStompDK/blob/master/core/service.js#L114
) Since it is overwritten i guess the old promise will not work and is not helping me to reconnect to the channel.

**Comment by davinkevin** [comment]
Which version do you use ?

Normaly, all the subscription shoud be 'replayed' after 5 seconds by defaut. https://github.com/davinkevin/AngularStompDK/issues/13

**Comment by davinkevin** [comment]
You can see an example of app doing reconnection automatically, because connection fail or because server cut the connection. 

https://github.com/davinkevin/spring-websocket-backend

![image](https://cloud.githubusercontent.com/assets/1970922/16439928/4f7c4958-3dbd-11e6-8c7c-79fe09567513.png)

If you click "Loose connection from server", the system will automatically relaunch all subscription registered in AngularStompDK.

**Comment by sakthig** [comment]
Thanks for the replies. This issue does not seem to be present in latest version.

Sorry for not checking the latest version in first place and troubling you :smile:

Thanks

**Comment by davinkevin** [comment]
😄
