### ISSUE TITLE
How can I add a header to unSubscribe

### ISSUE THREAD

**Issue by flacohenao** [davinkevin/AngularStompDK#46]
It is possible to add a header when the connection is lost (e.g. closing the tab on the browser) or just calling any of the methods 

**unSubscribeAll**
**unSubscribeOf**

thank you.

**Comment by davinkevin** [comment]
I don't find any information about sending headers in `unsubscribe` of the original Stomp.js lib : https://github.com/jmesnil/stomp-websocket/blob/master/lib/stomp.js#L396

AngularStompDK is just a wrapper, so if this is not present is the original library, I can't handle it.

**Comment by flacohenao** [comment]
Thank you very much, and sorry for writing the 'Question Help' here, but as you must know, there is not much about AngularStompSK on stackOverFlow

**Comment by davinkevin** [comment]
You don't have to apology for question here... ;) And you have a Label for "Question" 😄 

Can I close this issue ?

**Comment by flacohenao** [comment]
yes, you can. thank you.

2016-11-10 0:46 GMT-05:00 Davin Kevin <notifications@github.com>:
